// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantAPI.Data;

#nullable disable

namespace RestaurantAPI.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260327135219_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RestaurantAPI.Model.Entities.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int")
                        .HasColumnName("dishId");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("RestaurantAPI.Model.Entities.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Salads"
                        });
                });

            modelBuilder.Entity("RestaurantAPI.Model.Entities.Dishes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<bool>("Nuts")
                        .HasColumnType("bit")
                        .HasColumnName("nuts");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Spiciness")
                        .HasColumnType("int")
                        .HasColumnName("spiciness");

                    b.Property<bool>("Vegetarian")
                        .HasColumnType("bit")
                        .HasColumnName("vegetarian");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Image = "pizza1.jpg",
                            Name = "Margherita",
                            Nuts = false,
                            Price = 15.5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Image = "pizza2.jpg",
                            Name = "Pepperoni",
                            Nuts = false,
                            Price = 18m,
                            Spiciness = 1,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Image = "pizza3.jpg",
                            Name = "BBQ Chicken Pizza",
                            Nuts = false,
                            Price = 20m,
                            Spiciness = 2,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Image = "burger1.jpg",
                            Name = "Classic Burger",
                            Nuts = false,
                            Price = 12m,
                            Spiciness = 1,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Image = "burger2.jpg",
                            Name = "Cheeseburger",
                            Nuts = false,
                            Price = 13.5m,
                            Spiciness = 1,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Image = "burger3.jpg",
                            Name = "Veggie Burger",
                            Nuts = false,
                            Price = 11m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Image = "drink1.jpg",
                            Name = "Coca Cola",
                            Nuts = false,
                            Price = 3m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Image = "drink2.jpg",
                            Name = "Orange Juice",
                            Nuts = false,
                            Price = 4m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Image = "drink3.jpg",
                            Name = "Lemonade",
                            Nuts = false,
                            Price = 3.5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Image = "dessert1.jpg",
                            Name = "Chocolate Cake",
                            Nuts = true,
                            Price = 6m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Image = "dessert2.jpg",
                            Name = "Cheesecake",
                            Nuts = false,
                            Price = 6.5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Image = "dessert3.jpg",
                            Name = "Ice Cream",
                            Nuts = false,
                            Price = 5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Image = "salad1.jpg",
                            Name = "Caesar Salad",
                            Nuts = false,
                            Price = 9m,
                            Spiciness = 0,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Image = "salad2.jpg",
                            Name = "Greek Salad",
                            Nuts = false,
                            Price = 8.5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Image = "salad3.jpg",
                            Name = "Avocado Salad",
                            Nuts = true,
                            Price = 10m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Image = "pizza4.jpg",
                            Name = "Spicy Pizza",
                            Nuts = false,
                            Price = 19m,
                            Spiciness = 3,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Image = "burger4.jpg",
                            Name = "Double Burger",
                            Nuts = false,
                            Price = 15m,
                            Spiciness = 2,
                            Vegetarian = false
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Image = "drink4.jpg",
                            Name = "Mojito",
                            Nuts = false,
                            Price = 5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Image = "dessert4.jpg",
                            Name = "Brownie",
                            Nuts = true,
                            Price = 5.5m,
                            Spiciness = 0,
                            Vegetarian = true
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Image = "salad4.jpg",
                            Name = "Chicken Salad",
                            Nuts = false,
                            Price = 11m,
                            Spiciness = 1,
                            Vegetarian = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
